# Generated by Django 4.1.7 on 2023-04-27 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userprofile_is_maker_userprofile_is_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/avatar/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Описание профиля')),
                ('vk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка VK')),
                ('inst', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Instagram')),
                ('telegram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка Telegram')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/images/', verbose_name='Изображения для профиля')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='userProfile.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Изображения для профиля',
                'verbose_name_plural': 'Изображения в профилях',
                'ordering': ['id'],
            },
        ),
    ]
