# Generated by Django 4.1.7 on 2023-04-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_profile_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Остаток на счету'),
        ),
    ]
