# Generated by Django 4.1.7 on 2023-04-27 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_alter_profile_options_profile_is_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='service',
            new_name='profile',
        ),
    ]
