# Generated by Django 4.1.7 on 2023-04-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_rename_service_images_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=30, unique=True, verbose_name='Ник'),
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='profile/videos/', verbose_name='Изображения для профиля')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='userProfile.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Видео для профиля',
                'verbose_name_plural': 'Видео в профилях',
                'ordering': ['id'],
            },
        ),
    ]
