# Generated by Django 4.1.7 on 2023-04-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryservice',
            options={'ordering': ['id'], 'verbose_name': 'Категория услуг', 'verbose_name_plural': 'Категории услуг'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['id'], 'verbose_name': 'Изображения услуги', 'verbose_name_plural': 'Изображения услуг'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_at'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='produced',
            new_name='service',
        ),
    ]
