# Generated by Django 4.1.7 on 2023-04-19 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Produced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Название товара')),
                ('article_number', models.CharField(max_length=50, verbose_name='Артикул')),
                ('specifications', models.TextField(blank=True, null=True, verbose_name='Характеристики')),
                ('equipment', models.TextField(blank=True, null=True, verbose_name='Комплектация')),
                ('price', models.PositiveIntegerField(verbose_name='Цена товара')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опбуликовано')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makers.categorymakers', verbose_name='Категория товара')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец поста')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/', verbose_name='Общие изображения услуги')),
                ('produced', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='makers.produced', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Изображения товара',
                'verbose_name_plural': 'Изображения товаров',
                'ordering': ['id'],
            },
        ),
    ]
