# Generated by Django 4.1.7 on 2023-04-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymakers',
            options={'ordering': ['id'], 'verbose_name': 'Категория производителей', 'verbose_name_plural': 'Категории производителей'},
        ),
    ]
