# Generated by Django 4.1.7 on 2023-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0002_alter_categorymakers_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produced',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
