# Generated by Django 4.1.7 on 2023-04-19 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0003_produced_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produced',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Просмотры'),
        ),
    ]
