# Generated by Django 4.1.7 on 2023-04-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0005_remove_produced_view_count_viewer_produced_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produced',
            name='viewers',
            field=models.ManyToManyField(blank=True, to='makers.viewer'),
        ),
    ]
