# Generated by Django 4.1.7 on 2023-04-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0006_alter_produced_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewer',
            name='ipaddress',
        ),
    ]
