# Generated by Django 4.1.7 on 2023-04-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0008_produced_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produced',
            name='view_count',
        ),
        migrations.AddField(
            model_name='produced',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество просмотров'),
        ),
    ]
