# Generated by Django 4.1.7 on 2023-04-20 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0009_remove_produced_view_count_produced_views_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produced',
            old_name='views_count',
            new_name='views_counter',
        ),
    ]
