# Generated by Django 4.1.7 on 2023-04-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0010_rename_views_count_produced_views_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produced',
            name='viewers',
        ),
        migrations.RemoveField(
            model_name='produced',
            name='views_counter',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='produced/', verbose_name='Общие изображения услуги'),
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
