# Generated by Django 4.1.7 on 2023-04-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makers', '0011_remove_produced_viewers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produced/', verbose_name='Общие изображения услуги'),
        ),
    ]
